Add auth in rows
huggingface/datasets-server pull request #1427
Opened 2023-06-23 16:37 UTC by lhoestq

fix
```
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://huggingface.co/datasets/bigcode/the-stack-dedup/resolve/refs%2Fconvert%2Fparquet/bigcode--the-stack-dedup/parquet-train-00000-of-05140.parquet')
```

when doing pagination on the bigcode/the-stack-dedup which is gated

2023-06-23 16:42 UTC, severo approved these changes

2023-06-23 16:42 UTC, severo requested changes
I think the name of the header is missing

2023-06-23 22:41 UTC, lhoestq commented
fixed !

2023-06-26 07:23 UTC, severo approved these changes

2023-06-26 08:21 UTC, merged