remove first rows fallback variable
huggingface/datasets-server pull request #771
Opened 2023-02-04 16:06 UTC by JatinKumar001

Remove the FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE from the code.

2023-02-06 10:21 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets-server/pr_771). All of your documentation changes will be reflected on that endpoint.

2023-02-06 11:26 UTC, albertvillanova requested changes
Thanks for the fix @JatinKumar001.

We are working on a related issue (thanks @severo).
- #773

Once this PR is merged, could you please merge main branch into your branch?
```
git checkout remove-FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE
git fetch upstream main
git merge upstream/main
git push -u origin remove-FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE
```

2023-02-06 11:26 UTC, severo requested changes
Thanks a lot!

One small additional change is needed, and we're good!

2023-02-06 11:28 UTC, severo commented
Note that the CI is failing due to a temporary issue with the GitHub Actions (Azure repository of Ubuntu packages). It's not linked to the PR, and I'll relaunch the actions later, when the outage is over.

2023-02-06 12:59 UTC, JatinKumar001 commented on chart/templates/worker/first-rows/_container.tpl
> -    value: {{ .Values.firstRows.fallbackMaxDatasetSize | quote }}
Ok sure

2023-02-06 13:25 UTC, JatinKumar001 commented
Hey, can you tell me what I have to do to correct these errors?

2023-02-06 13:52 UTC, severo commented
Thanks.

For the CI errors, we have to wait until Azure fixes its repository, and then relaunch the github actions.

2023-02-06 14:21 UTC, albertvillanova commented
We have to wait until Canonical fixes their error on their servers:
- https://github.com/actions/runner-images/issues/7048

2023-02-07 12:33 UTC, severo commented
To finish this PR, you should:
- merge main into your branch
  ```
    git checkout remove-FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE
    git fetch upstream main
    git merge upstream/main
    git push -u origin remove-FIRST_ROWS_FALLBACK_MAX_DATASET_SIZE
    ```
- remove the two lines in `chart/values.yaml` at https://github.com/huggingface/datasets-server/blob/3bb80b725c361bb5072e14ffc82ab4838ad12405/chart/values.yaml#L285-L286

2023-02-07 15:48 UTC, severo commented
It seems like you still have not merged the main branch of this repository into your branch. Do you want us to help with that?

2023-02-07 15:53 UTC, JatinKumar001 commented
I done it and also create a new pull request 
#781

2023-02-07 16:23 UTC, severo commented
It seems like the branch you merged into your own branch is not the current main branch.

2023-02-08 10:11 UTC, albertvillanova approved these changes
@JatinKumar001 please note that you don't have to open a new pull request.

You only need to push to this PR the requested changes.

I think we have fixed the problems and this PR is already OK for merging. Do you agree @severo?
EDIT: we need to fix the CI errors first.

2023-02-08 10:13 UTC, albertvillanova requested changes
CI errors should be fixed first.

2023-02-08 10:27 UTC, albertvillanova approved these changes

2023-02-08 10:31 UTC, severo approved these changes
Thanks @JatinKumar001 for the contribution!

And thanks @albertvillanova to make it mergeable and for finding the bug (https://github.com/huggingface/datasets-server/pull/771/commits/712e87189b34f591fea5544f3b3e711d2fbfb95b)!

2023-02-08 10:41 UTC, merged