Generic worker
huggingface/datasets-server pull request #802
Opened 2023-02-09 16:31 UTC by severo

This PR allows a worker to process different job types. We can still dedicate workers to a sublist of jobs using a comma-separated list of the jobs in `WORKER_LOOP_ONLY_JOB_TYPES`.

This way, we will be able to reduce the allocated but unused resources.

As you can see in chart/env/prod.yaml, I let all the previous workers but added 20 instances of "genericWorker" that can process any job. If it works well, we can reduce the number of specific workers (maybe just /first-rows and /parquet-and-dataset-info) and increase the number of generic ones.

Fixes #737.

2023-02-09 16:34 UTC, HuggingFaceDocBuilder commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets-server/pr_802). All of your documentation changes will be reflected on that endpoint.

2023-02-13 14:25 UTC, AndreaFrancis requested changes

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/src/libcommon/queue.py
>          """Cancel all started jobs."""
```suggestion
        """Cancel all started jobs for a given type."""
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is True
```suggestion
    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is True
```suggestion
    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is True
```suggestion
    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is False
```suggestion
    assert not queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is True
```suggestion
    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is False
```suggestion
    assert not queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert (
```suggestion
    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset, config=test_config, split="split1")
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +        queue.is_job_in_process(job_type=test_type, dataset=test_dataset, config=test_config, split="split1") is True
```suggestion
        queue.is_job_in_process(job_type=test_type, dataset=test_dataset, config=test_config, split="split1")
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=job_type, dataset=test_dataset, config=None, split=None) is True
```suggestion
    assert queue.is_job_in_process(job_type=job_type, dataset=test_dataset, config=None, split=None)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    if only_job_types is not None and job_type not in only_job_types:
```suggestion
    if only_job_types and job_type not in only_job_types:
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +            job_info = queue.start_job(only_job_types=only_job_types)
Do you use job_info?

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is True
```suggestion
    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on libs/libcommon/tests/test_queue.py
> +    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset) is True
```suggestion
    assert queue.is_job_in_process(job_type=test_type, dataset=test_dataset)
```

2023-02-13 14:25 UTC, AndreaFrancis commented on services/worker/tests/test_loop.py
> +    loop.queue.is_job_in_process(
```suggestion
    assert loop.queue.is_job_in_process(
```

2023-02-13 14:25 UTC, AndreaFrancis commented on services/worker/tests/test_loop.py
> +    loop.queue.is_job_in_process(
```suggestion
    assert loop.queue.is_job_in_process(
```

2023-02-13 15:02 UTC, severo commented on libs/libcommon/tests/test_queue.py
> +            job_info = queue.start_job(only_job_types=only_job_types)
removing, thanks

2023-02-13 15:04 UTC, severo commented
Thanks! I fixed based on your comments (and even removed all occurrences of `is False` or `is True`). I rebased on main after https://github.com/huggingface/datasets-server/pull/805, so there should be new changes.

2023-02-13 15:11 UTC, AndreaFrancis approved these changes

2023-02-13 15:29 UTC, merged