Add partial cache entries for fan-in jobs
huggingface/datasets-server pull request #909
Opened 2023-03-08 14:12 UTC by lhoestq

Following discussion in https://github.com/huggingface/datasets-server/pull/900

I don't have a strong opinion on the name of the key we should store between "partial", "completeness" or others.
Therefore feel free to recommend another name or value type if you have better ideas.

I just like "partial" better because by default a job is not partial, so we just need to specify it when needed.

2023-03-08 14:16 UTC, HuggingFaceDocBuilder commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets-server/pr_909). All of your documentation changes will be reflected on that endpoint.

2023-03-08 16:22 UTC, severo requested changes
Thanks. We must add a migration split to add the field in all the existing entries (see the previous migrations).

And same comment as @AndreaFrancis: how will we set this field? In the case of /dataset--split-names, for example, the fan-in job runner will need:
- to know the list of all the config names
- to fetch all the cache entries for /config--split-names (from streaming and from dataset info, not important here)
and set "partial" if some cache entries are missing. But currently, the job runner does not have the list of all the config names. We have to change something in the code.

2023-03-08 16:25 UTC, severo commented
Referring to https://github.com/huggingface/datasets-server/pull/900#issuecomment-1460151662

Indeed, if we are comparing two lists, we could replace `partial: bool` with `progress` between 0 and 1.

2023-03-08 16:40 UTC, lhoestq commented
> It look good to me, just one question, where will we set the new "partial" field?

Maybe let me update `.compute()` to let allow it to return a potentially partial response

> But currently, the job runner does not have the list of all the config names. We have to change something in the code.

`dataset--split-names` can check in parent jobs for config names: in `/config-names` or in `/dataset-info`, and then combine results from `/split-names-from-streaming` or `/split-names-from-dataset-info`.

2023-03-08 16:44 UTC, severo commented
> dataset--split-names can check in parent jobs for config names: in /config-names or in /dataset-info, and then combine results from /split-names-from-streaming or /split-names-from-dataset-info.

Yes, but... for now, every processing step only knows about itself. We have no way to access the result of other processing steps (we would have to hard code things if we want to, or to change the logic, with an orchestrator, I think). To me, with the current logic, the list of configs should be given as an input parameter to the job...

2023-03-08 17:35 UTC, lhoestq commented
> We have no way to access the result of other processing steps (we would have to hard code things if we want to, or to change the logic, with an orchestrator, I think). To me, with the current logic, the list of configs should be given as an input parameter to the job...

You know the dataset name, so you know from where to get the list of config names in the cache. IMO it's ok to read the cache of parent jobs as long as we know what we're doing and it's tested. I don't think it's worth implementing an orchestrator just for that right now.

2023-03-08 17:50 UTC, lhoestq commented
Now `.compute()` must return a `JobResult`, which simply wraps the result content, and has two additional fields: complete and progress.

Those two fields are added to the cache entry when the job is computed

2023-03-08 21:35 UTC, lhoestq commented
Ah I forgot the migration. Will add it tomorrow

2023-03-08 22:58 UTC, AndreaFrancis reviewed
Thanks! It will be useful for the new aggregations

2023-03-09 10:07 UTC, severo requested changes
Thanks, adding `progress` will help handling the fan-in jobs.

Detail: I think we have to remove `complete` and only use `progress`.

2023-03-09 10:07 UTC, severo commented on services/worker/src/worker/job_runner.py
> +            raise ValueError(f"Progress should be between 0 and 1, but got {self.progress}")
conceptually: progress is continuous between 0 and 1, while complete is discrete: 0 or 1. progress is richer, and contains complete. Not really related, but it's like [fuzzy logic](https://en.wikipedia.org/wiki/Fuzzy_logic) vs binary logic.

2023-03-09 10:07 UTC, severo commented on services/worker/src/worker/job_runner.py
> +    def compute(self) -> JobResult:
nice abstraction

2023-03-09 10:09 UTC, severo commented
> You know the dataset name, so you know from where to get the list of config names in the cache. IMO it's ok to read the cache of parent jobs as long as we know what we're doing and it's tested. I don't think it's worth implementing an orchestrator just for that right now.
> 
> Also by carrying around config names you may end up with an outdated list of configs. Better check for the last version in the cache directly

Yes, I agree that we should do it without an orchestrator for now. Let's see the details in the next PR

2023-03-09 10:30 UTC, lhoestq commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
Ok let me remove `complete` - but in that case let's make sure we don't do bad float comparisons when checking for a result to be complete ;)

2023-03-09 10:35 UTC, severo commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
> bad float comparisons

What kind of issue could we have?

If there are risks, maybe we should extract the comparison in a dedicated method (`is_complete()`) and only use this to check the completeness.

2023-03-09 10:38 UTC, lhoestq commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
It's minor and shouldn't happen, so I don't think it's a concern actually.

I was referring to python issues like
```python
>>> 13371337133713371337 / 13371337133713371338 == 1.
True
```

2023-03-09 10:59 UTC, severo commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
Another way, to avoid this issue, is to have two fields:
- `total_parts`
- `computed_parts`

2023-03-09 11:09 UTC, lhoestq commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
I like that !

2023-03-09 11:21 UTC, lhoestq commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
Hmm actually not that much - it assumes we can count things which may not always be the case. I'll stick with `progress` x)

2023-03-09 11:29 UTC, lhoestq commented on services/worker/src/worker/job_runner.py
> +        if cached_response["complete"] is not None and not cached_response["complete"]:
I think we should only do this if `progress` exists and is < 1.

By default we can agree that a response is complete

2023-03-09 11:32 UTC, severo commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
> it assumes we can count things which may not always be the case

why? it can be 1 and 1. Or None.

2023-03-09 11:34 UTC, severo commented on services/worker/src/worker/job_runner.py
> +        if cached_response["complete"] is not None and not cached_response["complete"]:
(we could also force progress to exist - it's generally easier to work without having to manage None/Optional cases)

2023-03-09 12:48 UTC, severo commented on libs/libcommon/src/libcommon/simple_cache.py
> +        complete (`bool`): When the response is complete. Partial results keep being updated with subsequent jobs.
OK! It's also simpler conceptually to have one value. It's the responsibility of the job_runner to set the value properly.

2023-03-09 17:46 UTC, AndreaFrancis approved these changes
Great!

2023-03-09 17:46 UTC, AndreaFrancis commented on services/worker/tests/test_job_runner.py
> +    complete: Optional[bool] = None
```suggestion
```

2023-03-10 18:58 UTC, lhoestq commented
The only failing test is unrelated, see #920

2023-03-11 18:46 UTC, severo approved these changes

2023-03-11 18:46 UTC, severo commented on libs/libcommon/src/libcommon/simple_cache.py
> +        progress (`float`): Progress percentage if the result is not complete yet.
nit: percentage seems to imply that the value goes between 0 and 100. But the alternative names are worse (https://english.stackexchange.com/questions/275734/a-word-for-a-value-between-0-and-1-inclusive) so I think it's better to keep percentage 😛 (the type makes it clear below)

2023-03-11 18:46 UTC, severo commented on services/worker/src/worker/job_runner.py
> +        if cached_response["progress"] is not None and cached_response["progress"] < 1.0:
Could you please add a line in the function's docstring for that case? (or remove the list of cases from the docstring, if you feel it's useless)

2023-03-13 09:52 UTC, merged