check if /splits-name-from-* exists before processing it
huggingface/datasets-server pull request #995
Opened 2023-03-28 19:24 UTC by AndreaFrancis

Closes https://github.com/huggingface/datasets-server/issues/963

Adding validation on split names - config level job runners to throw an error if the response of the same info has already been computed.

2023-03-28 19:27 UTC, HuggingFaceDocBuilder commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/datasets-server/pr_995). All of your documentation changes will be reflected on that endpoint.

2023-03-28 19:58 UTC, severo requested changes

2023-03-28 19:58 UTC, severo commented on services/worker/src/worker/job_runners/config/split_names_from_dataset_info.py
> +        if streaming_response["http_status"] == HTTPStatus.OK:
we also have to check the job runner version and the git revision.

2023-03-29 16:11 UTC, AndreaFrancis commented on services/worker/src/worker/job_runners/config/split_names_from_dataset_info.py
> +        super().__init__(message, HTTPStatus.INTERNAL_SERVER_ERROR, "ResponseAlreadyComputedError", cause, True)
For now, I could create an issue to review all the other and modify them according to a better error code, wdyt?

2023-03-29 19:17 UTC, AndreaFrancis commented on services/worker/src/worker/job_runners/config/split_names_from_dataset_info.py
> +        dataset_git_revision = self.get_dataset_git_revision()
I added a validation in https://github.com/huggingface/datasets-server/pull/995/commits/588f6e0f7911e24354630aeb48b466d87affa22c before return job dataset_git_revision

2023-03-29 19:24 UTC, AndreaFrancis commented on services/worker/src/worker/job_runners/config/split_names_from_dataset_info.py
> +        super().__init__(message, HTTPStatus.INTERNAL_SERVER_ERROR, "ResponseAlreadyComputedError", cause, True)
I created this issue https://github.com/huggingface/datasets-server/issues/998

2023-03-30 09:16 UTC, severo approved these changes

2023-03-30 09:16 UTC, severo commented on services/worker/src/worker/job_runner.py
> +    dataset_git_revision: Optional[str] = None
nit: as this field is not meant to be accessed directly (it's a cache), I would prefer to prefix it with `_`
```suggestion
    _dataset_git_revision: Optional[str] = None
```

2023-03-30 09:16 UTC, severo commented on services/worker/src/worker/job_runner.py
> +        return self.dataset_git_revision
```suggestion
        if self._dataset_git_revision is None:
            self._dataset_git_revision = get_dataset_git_revision(
                dataset=self.dataset, hf_endpoint=self.common_config.hf_endpoint, hf_token=self.common_config.hf_token
            )
        return self._dataset_git_revision
```

2023-03-30 19:20 UTC, merged